<?php
/**
 * Tests for Franer_Public.
 *
 * @package Franer
 */

/**
 * Verifies the public-facing render helpers and security headers.
 */
class PublicTest extends WP_UnitTestCase {

	/**
	 * The standalone activity page must advertise same-origin-only framing so the
	 * authenticated submit shell cannot be framed by third-party origins.
	 *
	 * @return void
	 */
	public function test_frame_protection_headers() {
		$public  = new Franer_Public( 'franer', FRANER_VERSION );
		$headers = $public->frame_protection_headers();

		$this->assertSame( 'SAMEORIGIN', $headers['X-Frame-Options'] );
		$this->assertSame( "frame-ancestors 'self'", $headers['Content-Security-Policy'] );
	}

	/**
	 * Integrators may tighten the anti-framing headers via the filter.
	 *
	 * @return void
	 */
	public function test_frame_protection_headers_are_filterable() {
		add_filter(
			'franer_frame_protection_headers',
			static function ( $headers ) {
				$headers['X-Frame-Options'] = 'DENY';
				return $headers;
			}
		);

		$public  = new Franer_Public( 'franer', FRANER_VERSION );
		$headers = $public->frame_protection_headers();

		$this->assertSame( 'DENY', $headers['X-Frame-Options'] );
	}

	/**
	 * Create a published, viewable Franer site with the given activity HTML.
	 *
	 * @param string $html The raw activity HTML (stored in post_content).
	 * @return int The created post ID.
	 */
	private function create_viewable_site( $html ) {
		$post_id = self::factory()->post->create(
			array(
				'post_type'   => 'franer_site',
				'post_status' => 'publish',
				'post_title'  => 'Comment Activity',
			)
		);

		// Store the activity HTML exactly like the real save path (KSES bypassed),
		// so <script>/<style> blocks survive into post_content.
		Franer_Site_Repository::set_raw_html( $post_id, $html );

		update_post_meta( $post_id, '_franer_slug', 'comments-demo' );
		update_post_meta( $post_id, '_franer_enabled', '1' );
		update_post_meta( $post_id, '_franer_allowed_roles', array( 'subscriber' ) );

		return $post_id;
	}

	/**
	 * Public rendering must strip HTML and inline-JS comments from the iframe
	 * srcdoc, while the stored source (and the admin editor's settings view) keeps
	 * its comments intact.
	 *
	 * @return void
	 */
	public function test_public_render_strips_comments_but_source_is_preserved() {
		$html = "<!-- GENERATED BY PROMPT: do not leak -->\n"
			. "<style>/* css stays */ body{color:#000}</style>\n"
			. "<div>Question</div>\n"
			. "<script>\n// js line comment\nvar keep = \"https://example.com\"; /* js block */\n</script>";

		$post_id = $this->create_viewable_site( $html );

		$subscriber = self::factory()->user->create( array( 'role' => 'subscriber' ) );
		wp_set_current_user( $subscriber );

		$output = do_shortcode( '[franer slug="comments-demo"]' );

		// The rendered srcdoc must not carry HTML or JS comments...
		$this->assertStringNotContainsString( 'GENERATED BY PROMPT', $output );
		$this->assertStringNotContainsString( 'js line comment', $output );
		$this->assertStringNotContainsString( 'js block', $output );
		// ...but CSS comments and string contents survive.
		$this->assertStringContainsString( 'css stays', $output );
		$this->assertStringContainsString( 'https://example.com', $output );

		// The stored source (used by the admin editor) keeps every comment.
		$settings = ( new Franer_Site_Repository() )->get_settings( $post_id );
		$this->assertStringContainsString( 'GENERATED BY PROMPT', $settings['html'] );
		$this->assertStringContainsString( '// js line comment', $settings['html'] );
		$this->assertStringContainsString( '/* js block */', $settings['html'] );
	}
}
